apiVersion: v1
kind: Service
metadata:
  name: dev-rep-mongo
spec:
  ports:
  - port: 27017
    name: dev-rep-mongo
  selector:
    app: dev-rep-mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-rep-mongo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dev-rep-mongo
spec:
  selector:
    matchLabels:
      app: dev-rep-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-rep-mongo
    spec:
      containers:
      - image: mongo:3.7-jessie
        name: dev-rep-mongo        
        ports:
        - containerPort: 27017
          name: dev-rep-mongo
        volumeMounts:
        - name: dev-rep-mongo-persistent-storage
          mountPath: /data/db
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"
      volumes:
      - name: dev-rep-mongo-persistent-storage
        persistentVolumeClaim:
          claimName: dev-rep-mongo-pv-claim
