apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: device-report-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-report-handler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: device-report-handler
    spec:      
      containers:
      - image: nebulaetpm/devices-report.backend.devices-report-recepcionis:0.0.1
        name: device-report-handler
        env:        
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        - name: MONGODB_URL
          value: mongodb://device-report-mongo:27017
        - name: MONGODB_DB_NAME
          value: DevicesReport
        - name: DEVICE_ALARM_TEMPERATURE_MAX
          value: 60
        - name: DEVICE_ALARM_CPU_USAGE_PERCENTAGE_MAX
          value: 50
        - name: DEVICE_ALARM_RAM_USAGE_PERCENTAGE_MAX
          value: 70
        - name: DEVICE_ALARM_VOLUME_USAGE_PERCENTAGE_MAX
          value: 70        