apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dev-rep-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-rep-handler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-rep-handler
    spec:      
      containers:
      - image: nebulaetpm/devices-report.backend.devices-report-handler:0.0.5
        name: dev-rep-handler
        volumeMounts:
        - name: google-application-credentials
          mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
          readOnly: true
        env:        
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        - name: MONGODB_URL
          value: mongodb://dev-rep-mongo:27017
        - name: MONGODB_DB_NAME
          value: DevicesReport
        - name: DEVICE_ALARM_TEMPERATURE_MAX
          value: '60'
        - name: DEVICE_ALARM_CPU_USAGE_PERCENTAGE_MAX
          value: '50'
        - name: DEVICE_ALARM_RAM_USAGE_PERCENTAGE_MAX
          value: '70'
        - name: DEVICE_ALARM_VOLUME_USAGE_PERCENTAGE_MAX
          value: '70' 
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/GOOGLE_APPLICATION_CREDENTIALS/gcloud-service-key.json
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials       
      