apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dev-rep-recep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-rep-recep
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev-rep-recep
    spec:      
      containers:
      - image: nebulaetpm/devices-report.backend.devices-report-recepcionist:0.0.2
        name: dev-rep-recep
        env:        
        - name: EVENT_STORE_BROKER_TYPE
          value: PUBSUB
        - name: EVENT_STORE_BROKER_EVENTS_TOPIC
          value: events
        - name: EVENT_STORE_STORE_TYPE
          value: MONGO
        - name: EVENT_STORE_STORE_URL
          value: mongodb://dbevents-0.dbevents:27017,dbevents-1.dbevents:27017,dbevents-2.dbevents:27017/test?replicaSet=rs0
        - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
          value: Aggregates
        - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
          value: EventStore
        - name: IOT_BROKER_TYPE
          value: PUBSUB
        - name: IOT_BROKER_TOPIC
          value: devices-iot        